# basic options
title: Spam Detection Using Machine Learning
author: Rocio Krebs
email: rk50@students.uwf.edu
description: Spam detection using machine learning
github_username:  rokrebs

# Build settings
markdown: kramdown
theme: minima
