# basic options
title: Midterm Project
author: Rocio Krebs
email: rk50@students.uwf.edu
description: Spam detectionusing machine learning
github_username:  rokrebs

# Build settings
markdown: kramdown
theme: minima
